### PR TITLE
button text changed to Order

### PR DESCRIPTION
**Pull request by mihiHarshana**
button text changed to Order ., py increased to 2 aligned to right

### CODE REVIEW

**Comment by mihiHarshana** [comment]
@HarshaAbeyvickrama  Please review

**Review by HarshaAbeyvickrama — CHANGES_REQUESTED** [review]
Remove the margin at the right side to the button. @HarshaAbeyvickrama  Please review

**Comment by mihiHarshana** [comment]
Removed requested padding to align it with the right

**Review by HarshaAbeyvickrama — APPROVED** [review]
Approved

**Pull request merged**
